### ISSUE TITLE
Error: Uncaught [ReferenceError: require is not defined]

### ISSUE THREAD

**Issue by gplusdotgr** [badeball/karma-jsdom-launcher#21]
Hey everyone, I am getting the following:
```
26 03 2018 12:05:31.992:INFO [karma]: Karma v2.0.0 server started at http://0.0.0.0:9876/
26 03 2018 12:05:31.994:INFO [launcher]: Launching browsers PhantomJS, jsdom with unlimited concurrency
26 03 2018 12:05:32.019:INFO [launcher]: Starting browser PhantomJS
26 03 2018 12:05:32.034:INFO [launcher]: Starting browser jsdom
26 03 2018 12:05:32.319:INFO [Mozilla/5.0 (darwin) AppleWebKit/537.36 (KHTML, like Gecko) jsdom/11.6.2]: Connected on socket gVvFcOIlyTnT5DwWAAAA with id 4640999
Error: Uncaught [ReferenceError: require is not defined]
    at reportException (/Users/katsanos/frontend/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
    at processJavaScript (/Users/katsanos/frontend/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:192:7)
    at HTMLScriptElementImpl._innerEval (/Users/katsanos/frontend/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:122:5)
    at /Users/katsanos/frontend/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:31:22
    at Object.check (/Users/katsanos/frontend/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:74:11)
    at Object.check (/Users/katsanos/frontend/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:77:23)
    at Object.check (/Users/katsanos/frontend/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:77:23)
    at Object.check (/Users/katsanos/frontend/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:77:23)
    at Object.check (/Users/katsanos/frontend/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:77:23)
    at Object.check (/Users/katsanos/frontend/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:77:23)
    at Object.check (/Users/katsanos/frontend/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:77:23)
    at Object.check (/Users/katsanos/frontend/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:77:23)
    at /Users/katsanos/frontend/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:93:12
    at wrappedEnqueued (/Users/katsanos/frontend/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:255:16)
    at Request.request [as _callback] (/Users/katsanos/frontend/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:203:9)
    at Request.self.callback (/Users/katsanos/frontend/node_modules/request/request.js:186:22)
    at Request.emit (events.js:160:13)
    at Request.<anonymous> (/Users/katsanos/frontend/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:160:13)
    at IncomingMessage.<anonymous> (/Users/katsanos/frontend/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:255:19)
    at IncomingMessage.emit (events.js:165:20) ReferenceError: require is not defined
    at Object.<anonymous> (http://localhost:9876/absolute/Users/katsanos/frontend/src/polyfill.js?bfa7df36fda9612c38466460ce848e3f2edf35ba:122:1)
    at __webpack_require__ (http://localhost:9876/absolute/Users/katsanos/frontend/src/polyfill.js?bfa7df36fda9612c38466460ce848e3f2edf35ba:20:30)
    at Object.<anonymous> (http://localhost:9876/absolute/Users/katsanos/frontend/src/polyfill.js?bfa7df36fda9612c38466460ce848e3f2edf35ba:111:1)
    at __webpack_require__ (http://localhost:9876/absolute/Users/katsanos/frontend/src/polyfill.js?bfa7df36fda9612c38466460ce848e3f2edf35ba:20:30)
    at path (http://localhost:9876/absolute/Users/katsanos/frontend/src/polyfill.js?bfa7df36fda9612c38466460ce848e3f2edf35ba:63:18)
    at http://localhost:9876/absolute/Users/katsanos/frontend/src/polyfill.js?bfa7df36fda9612c38466460ce848e3f2edf35ba:66:10
    at Script.runInContext (vm.js:74:29)
    at Object.runInContext (vm.js:184:6)
    at processJavaScript (/Users/katsanos/frontend/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:190:10)
    at HTMLScriptElementImpl._innerEval (/Users/katsanos/frontend/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:122:5)
Error: Uncaught [ReferenceError: require is not defined]
    at reportException (/Users/katsanos/frontend/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
    at processJavaScript (/Users/katsanos/frontend/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:192:7)
    at HTMLScriptElementImpl._innerEval (/Users/katsanos/frontend/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:122:5)
    at /Users/katsanos/frontend/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:31:22
    at Object.check (/Users/katsanos/frontend/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:74:11)
    at Object.check (/Users/katsanos/frontend/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:77:23)
    at Object.check (/Users/katsanos/frontend/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:77:23)
    at Object.check (/Users/katsanos/frontend/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:77:23)
    at Object.check (/Users/katsanos/frontend/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:77:23)
    at Object.check (/Users/katsanos/frontend/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:77:23)
    at Object.check (/Users/katsanos/frontend/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:77:23)
    at Object.check (/Users/katsanos/frontend/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:77:23)
    at Object.check (/Users/katsanos/frontend/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:77:23)
    at /Users/katsanos/frontend/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:93:12
    at wrappedEnqueued (/Users/katsanos/frontend/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:255:16)
    at Request.request [as _callback] (/Users/katsanos/frontend/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:203:9)
    at Request.self.callback (/Users/katsanos/frontend/node_modules/request/request.js:186:22)
    at Request.emit (events.js:160:13)
    at Request.<anonymous> (/Users/katsanos/frontend/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:160:13)
    at IncomingMessage.<anonymous> (/Users/katsanos/frontend/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:255:19) ReferenceError: require is not defined
    at Object.4 (http://localhost:9876/base/setup.js?83b2f7a72c17025c9bf79954971a2d3d0c88c2f1:448:1)
    at __webpack_require__ (http://localhost:9876/base/setup.js?83b2f7a72c17025c9bf79954971a2d3d0c88c2f1:20:30)
    at Object.<anonymous> (http://localhost:9876/base/setup.js?83b2f7a72c17025c9bf79954971a2d3d0c88c2f1:79:13)
    at Object.242 (http://localhost:9876/base/setup.js?83b2f7a72c17025c9bf79954971a2d3d0c88c2f1:364:30)
    at __webpack_require__ (http://localhost:9876/base/setup.js?83b2f7a72c17025c9bf79954971a2d3d0c88c2f1:20:30)
    at 242.Object.defineProperty.value (http://localhost:9876/base/setup.js?83b2f7a72c17025c9bf79954971a2d3d0c88c2f1:63:18)
    at http://localhost:9876/base/setup.js?83b2f7a72c17025c9bf79954971a2d3d0c88c2f1:66:10
    at Script.runInContext (vm.js:74:29)
    at Object.runInContext (vm.js:184:6)
    at processJavaScript (/Users/katsanos/frontend/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:190:10)
26 03 2018 12:05:32.589:WARN [reporter]: SourceMap position not found for trace: undefined
26 03 2018 12:05:32.590:WARN [reporter]: SourceMap position not found for trace: undefined
Mozilla/5.0 (darwin) AppleWebKit/537.36 (KHTML, like Gecko) jsdom/11.6.2 ERROR
  {
    "message": "require is not defined\nat webpack:///external%20%22whatwg-fetch/fetch%22:1:0 <- /Users/katsanos/frontend/src/polyfill.js:122:1\n\nReferenceError: require is not defined\n    at Object.<anonymous> (webpack:///external%20%22whatwg-fetch/fetch%22:1:0 <- /Users/katsanos/frontend/src/polyfill.js:122:1)\n    at __webpack_require__ (webpack:///webpack/bootstrap%205d20b05616974f9ceb9f:19:0 <- /Users/katsanos/frontend/src/polyfill.js:20:30)\n    at Object.<anonymous> (webpack:///src/polyfill.js:1:0 <- /Users/katsanos/frontend/src/polyfill.js:111:1)\n    at __webpack_require__ (webpack:///webpack/bootstrap%205d20b05616974f9ceb9f:19:0 <- /Users/katsanos/frontend/src/polyfill.js:20:30)\n    at path (webpack:///webpack/bootstrap%205d20b05616974f9ceb9f:62:0 <- /Users/katsanos/frontend/src/polyfill.js:63:18)\n    at /Users/katsanos/frontend/src/polyfill.js:66:10\n    at Script.runInContext (vm.js:74:29)\n    at Object.runInContext (vm.js:184:6)\n    at processJavaScript (/Users/katsanos/frontend/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:190:10)\n    at HTMLScriptElementImpl._innerEval (/Users/katsanos/frontend/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:122:5)",
    "str": "require is not defined\nat webpack:///external%20%22whatwg-fetch/fetch%22:1:0 <- /Users/katsanos/frontend/src/polyfill.js:122:1\n\nReferenceError: require is not defined\n    at Object.<anonymous> (webpack:///external%20%22whatwg-fetch/fetch%22:1:0 <- /Users/katsanos/frontend/src/polyfill.js:122:1)\n    at __webpack_require__ (webpack:///webpack/bootstrap%205d20b05616974f9ceb9f:19:0 <- /Users/katsanos/frontend/src/polyfill.js:20:30)\n    at Object.<anonymous> (webpack:///src/polyfill.js:1:0 <- /Users/katsanos/frontend/src/polyfill.js:111:1)\n    at __webpack_require__ (webpack:///webpack/bootstrap%205d20b05616974f9ceb9f:19:0 <- /Users/katsanos/frontend/src/polyfill.js:20:30)\n    at path (webpack:///webpack/bootstrap%205d20b05616974f9ceb9f:62:0 <- /Users/katsanos/frontend/src/polyfill.js:63:18)\n    at /Users/katsanos/frontend/src/polyfill.js:66:10\n    at Script.runInContext (vm.js:74:29)\n    at Object.runInContext (vm.js:184:6)\n    at processJavaScript (/Users/katsanos/frontend/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:190:10)\n    at HTMLScriptElementImpl._innerEval (/Users/katsanos/frontend/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:122:5)"
  }
```

That's my setup.js in my unit tests

```
import chai from 'chai';
import 'jsdom-global/register';
import chaiAsPromised from 'chai-as-promised';
import sinonChai from 'sinon-chai';
import mapsAPI from 'mocks/maps';
import accountApi from 'mocks/account';
import sinon from 'sinon';
import 'sinon-as-promised';
import 'babel-polyfill';
```

and I am running this as 

`    "unit": "cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run",`

That's my karma.conf

```
// This is a karma config file. For more details see http://karma-runner.github.io/0.13/config/configuration-file.html
// we are also using it with karma-webpack https://github.com/webpack/karma-webpack

const webpackConfig = require('../../build/webpack.test.conf');

module.exports = (config) => {
  config.set({
    // to run in additional browsers:
    //   1. install corresponding karma launcher http://karma-runner.github.io/0.13/config/browsers.html
    //   2. add it to the `browsers` array below.
    browsers: ['PhantomJS', 'jsdom'],
    frameworks: ['mocha', 'sinon-chai'],
    reporters: ['mocha', 'coverage'],
    files: [
      '../../src/polyfill.js',
      './setup.js',
      './index.js',
    ],
    preprocessors: {
      '../../src/polyfill.js': ['webpack', 'sourcemap'],
      './index.js': ['webpack', 'sourcemap'],
      './setup.js': ['webpack', 'sourcemap'],
      [require.resolve('chai-as-promised')]: ['webpack'],
    },
    webpack: webpackConfig,
    webpackMiddleware: {
      noInfo: true,
    },
    mochaReporter: {
      showDiff: true,
    },
    coverageReporter: {
      dir: './coverage',
      reporters: [
        { type: 'lcov', subdir: '.' },
        { type: 'json-summary', subdir: '.', file: 'report.json' },
        { type: 'text-summary' },
      ],
      type: 'in-memory',
      check: {
        global: {
          statements: 80,
          lines: 80,
          functions: 75,
          branches: 75,
        },
      },
    },
  });
};
```

**Comment by badeball** [comment]
Hi, @gkatsanos

This launcher will provide the jsdom environment for you. Therefore, you probably don't need to / want to import jsdom-global. Can you remove this and see if the error still persists?

**Comment by gplusdotgr** [comment]
Yep, I think it's good. @eddyerburgh I think you should update [the documention in vue-test-utils here](https://vue-test-utils.vuejs.org/en/guides/choosing-a-test-runner.html) and drop the import/require part and replace it with the launcher.
